events {}

http {
    server {
        listen 80;

        location /api/products/ {
            proxy_pass http://products-svc-s22:8143/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/products {
            proxy_pass http://products-svc-s22:8143/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
